const shoeList = [
  {
    Id: 1,
    name: "Custom Chuck 70 Canvas By You",
    category: "UNISEX",
    subcategory: "HIGH TOP SHOE",
    url: "shoe1.jpg",
    price: 1000,
    qnty: 0,
  },
  {
    Id: 2,
    name: "Custom Chuck 70 Canvas By You",
    category: "Men's Shoe",
    subcategory: "HIGH TOP SHOE",
    url: "shoe2.jpg",
    price: 2000,
    qnty: 0,
  },
  {
    Id: 3,
    name: "Custom Chuck 70 Canvas By You",
    category: "Men's Shoe",
    subcategory: "HIGH TOP SHOE",
    url: "shoe3.jpg",
    price: 3000,
    qnty: 0,
  },
  {
    Id: 4,
    name: "Custom Chuck 70 Canvas By You",
    category: "Men's Shoe",
    subcategory: "HIGH TOP SHOE",
    url: "shoe4.jpg",
    price: 1500,
    qnty: 0,
  },
  {
    Id: 5,
    name: "Custom Chuck 70 Canvas By You",
    category: "Men's Shoe",
    subcategory: "HIGH TOP SHOE",
    url: "shoe5.jpg",
    price: 2500,
    qnty: 0,
  },
  {
    Id: 6,
    name: "Custom Chuck 70 Canvas By You",
    category: "Women's Shoe",
    subcategory: "HIGH TOP SHOE",
    url: "shoe6.jpg",
    price: 1000,
    qnty: 0,
  },
  {
    Id: 7,
    name: "Custom Chuck 70 Canvas By You",
    category: "Women's Shoe",
    subcategory: "HIGH TOP SHOE",
    url: "shoe7.jpg",
    price: 2000,
    qnty: 0,
  },
  {
    Id: 8,
    name: "Custom Chuck 70 Canvas By You",
    category: "Women's Shoe",
    subcategory: "HIGH TOP SHOE",
    url: "shoe8.jpg",
    price: 3000,
    qnty: 0,
  },
  {
    Id: 9,
    name: "Custom Chuck 70 Canvas By You",
    category: "Women's Shoe",
    subcategory: "HIGH TOP SHOE",
    url: "shoe9.jpg",
    price: 1500,
    qnty: 0,
  },
  {
    Id: 10,
    name: "Custom Chuck 70 Canvas By You",
    category: "Women's Shoe",
    subcategory: "HIGH TOP SHOE",
    url: "shoe10.jpg",
    price: 2500,
    qnty: 0,
  },
  {
    Id: 11,
    name: "Custom Chuck 70 Leather By You",
    category: "Women's Shoe",
    subcategory: "LOW TOP SHOE",
    url: "shoe11.jpg",
    price: 2500,
    qnty: 0,
  },
  {
    Id: 12,
    name: "Custom Chuck 70 Leather By You",
    category: "UNISEX",
    subcategory: "LOW TOP SHOE",
    url: "shoe12.jpg",
    price: 3500,
    qnty: 0,
  },
  {
    Id: 13,
    name: "Custom Chuck 70 Leather By You",
    category: "Women's Shoe",
    subcategory: "LOW TOP SHOE",
    url: "shoe13.jpg",
    price: 1500,
    qnty: 0,
  },
  {
    Id: 14,
    name: "Custom Chuck 70 Leather By You",
    category: "UNISEX",
    subcategory: "LOW TOP SHOE",
    url: "shoe14.jpg",
    price: 500,

    qnty: 0,
  },
  {
    Id: 15,
    name: "Custom Chuck 70 Leather By You",
    category: "UNISEX",
    subcategory: "LOW TOP SHOE",
    url: "shoe15.jpg",
    price: 1000,
    qnty: 0,
  },
  {
    Id: 16,
    name: "Custom Chuck 70 Leather By You",
    category: "Women's Shoe",
    subcategory: "LOW TOP SHOE",
    url: "shoe16.jpg",
    price: 2500,
    qnty: 0,
  },
  {
    Id: 17,
    name: "Custom Chuck 70 Leather By You",
    category: "UNISEX",
    subcategory: "LOW TOP SHOE",
    url: "shoe17.jpg",
    price: 3500,
    qnty: 0,
  },
  {
    Id: 18,
    name: "Custom Chuck 70 Leather By You",
    category: "UNISEX",
    subcategory: "LOW TOP SHOE",
    url: "shoe18.jpg",
    price: 2000,
    qnty: 0,
  },
  {
    Id: 19,
    name: "Custom Chuck 70 Leather By You",
    category: "Women's Shoe",
    subcategory: "LOW TOP SHOE",
    url: "shoe19.jpg",
    price: 2500,
    qnty: 0,
  },
  {
    Id: 20,
    name: "Custom Chuck 70 Leather By You",
    category: "Women's Shoe",
    subcategory: "LOW TOP SHOE",
    url: "shoe20.jpg",
    price: 4500,
    qnty: 0,
  },
];
export default shoeList;
